apiVersion: v1
kind: Pod
metadata:
  name: taint-node-selector-exp-1
  labels:
    name: taint-node-selector-exp-1
spec:
  containers:
  - name: taint-node-selector-exp-1
    image: nginx
    ports:
      - containerPort: 80
  nodeSelector:
    custom-label-kubernetes.io/disk_allocate: ssd
    