apiVersion: v1
kind: Pod
metadata:
  name: node-selector-example
  labels:
    name: node-selector-example
spec:
  containers:
  - name: node-selector-example
    image: nginx
    resources:
    ports:
      - containerPort: 80
  tolerations:
  - key: "custom-label.kubernetes.io"
    operator: "Equal"
    value: "highcpuusages" 
    effect: "NoSchedule"
