apiVersion: v1
kind: Pod
metadata:
  name: node-selector-example
  labels:
    name: node-selector-example
spec:
  containers:
  - name: node-selector-example
    image: nginx
    resources:
    ports:
      - containerPort: 80
  nodeSelector: 
    custom-label.kubernetes.io/disk_allocate: ssd